MeasureAuthoringTool/MeasureAuthoringTool

src/main/java/mat/client/measure/ManageMeasurePresenter.java, src/main/java/mat/server/service/duplibrarys/LibraryNameDuplicateChecker.java
Develop was behind master, so I'm bringing it back up to speed
=> Fixing develop branch by pulling in master's changes

pom.xml, src/main/java/liquibase/addMeasureModelColumn.xml, src/main/java/liquibase/changelog.xml, src/main/java/mat/client/measure/AbstractNewMeasureView.java, src/main/java/mat/client/measure/DetailDisplay.java, src/main/java/mat/client/measure/ManageMeasureDetailModel.java, src/main/java/mat/client/measure/ManageMeasurePresenter.java, src/main/java/mat/client/measure/NewCompositeMeasureView.java, src/main/java/mat/client/measure/NewMeasureView.java, src/main/java/mat/client/shared/MessageDelegate.java, src/main/java/mat/model/clause/Measure.java, src/main/java/mat/server/MeasureLibraryServiceImpl.java, src/main/java/mat/server/clause/MeasureCloningServiceImpl.java, src/main/java/mat/server/util/ManageMeasureDetailModelConversions.java, src/main/java/mat/shared/measure/measuredetails/models/GeneralInformationModel.java, src/main/java/mat/shared/measure/measuredetails/translate/ManageMeasureDetailModelMapper.java, src/main/java/mat/shared/model/util/MeasureDetailsUtil.java, src/main/resources/MeasureDetailsModelMapping.xml, src/test/java/mat/client/measure/AbstractNewMeasureViewTest.java, war/Mat.css
Added Model Type(FHIR/QDM) in create measure and create composite  measure view
1. Create Measure view
2. Create Composite Measure View
In progress: Updating test cases...
=> Add Model Type to new/draft/cloned Measures

src/main/java/mat/client/measure/AbstractNewMeasureView.java, src/main/java/mat/client/shared/MessageDelegate.java, src/main/java/mat/server/MeasureLibraryServiceImpl.java
fixed Defect: QDM is not selectable on "create new measure" in `Add Model Type to new Measures`
=> QDM is not selectable on "create new measure"

src/main/java/mat/client/measure/ManageMeasureSearchModel.java, src/main/java/mat/client/shared/MeasureLibraryResultTable.java, src/main/java/mat/dao/clause/impl/MeasureDAOImpl.java, src/main/java/mat/model/clause/MeasureShareDTO.java, src/main/java/mat/server/MeasureLibraryServiceImpl.java, src/main/java/mat/server/util/ManageMeasureDetailModelConversions.java, src/main/java/mat/shared/model/util/MeasureDetailsUtil.java
Measure Library - Recent Activity Grid - Add Measure Type to Grid Row
Measure Library - My Measures Grid - Add Measure Type to Grid Row
=> Measure Library - Recent Activity Grid - Add Measure Type to Grid Row

pom.xml, src/main/java/mat/server/cqlparser/ReverseEngineerListener.java
Adding a function to not strip white spaces out while reverse engineering the cql file. This will fix the tuple bug the MAT is experiencing
=> Hotfix for MAT 5.8.3

src/main/java/mat/client/admin/ManageBonnieTokenView.java, src/main/java/mat/client/admin/ManageOrganizationView.java, src/main/java/mat/client/admin/ManageUsersSearchView.java
Handling Cross-site Scripting (XSS) using GWT SafeHtmlUtils
=> MAT-118 XSS in OrgName and Name fields

src/main/java/mat/client/MainLayout.java, war/Mat.css
MAT header when feature flag is 'OFF'
New Feature: MAT header when feature flag is 'ON'
=> MAT 433 Adding Top Level FHIR Identifier

src/main/java/mat/client/clause/QDSAttributesService.java, src/main/java/mat/client/clause/QDSAttributesServiceAsync.java, src/main/java/mat/client/cqlworkspace/InsertAttributeBuilderDialogBox.java, src/main/java/mat/server/CQLConstantServiceImpl.java, src/main/java/mat/server/CqlAttributesRemoteCallService.java, src/main/java/mat/server/clause/QDSAttributesServiceImpl.java, src/test/java/mat/server/CqlAttributesRemoteCallServiceTest.java
Rework based on issues identified by Chris in QA testing. 
Retrieving FHIR DataType from "fhirResource" and FHIR Attributes from "fhirElement"
Also handled a set of attributes to be displayed based on selected Datatype.
=> MAT-478 rework to get fhirResource and fhirElement fields

src/main/java/mat/client/CqlLibraryPresenter.java, src/main/java/mat/client/advancedsearch/AdvancedSearchPanel.java, src/main/java/mat/dao/clause/impl/CQLLibraryDAOImpl.java, src/main/java/mat/shared/SearchModel.java
Adding a filter for CQLLibrary search for ALL,FHIR,QDM measure types.
=> Implemented Story https://jira.cms.gov/browse/MAT-526

README.md, src/main/java/mat/client/measure/ManageMeasurePresenter.java, src/main/java/mat/client/measure/MeasureSearchView.java
https://jira.cms.gov/browse/MAT-584
- Added a label showing # of selected rows.
- Added a link that only shows up when a row is selected to clear selected rows.
- Added a missing env var in README.md
=> Implemented Story MAT-584 Allow user to clear selected grid rows.

src/main/java/mat/client/login/FirstLoginPresenter.java, src/main/java/mat/client/login/TempPwdLoginPresenter.java, src/main/java/mat/client/login/service/LoginService.java, src/main/java/mat/client/login/service/LoginServiceAsync.java, src/main/java/mat/client/myAccount/ChangePasswordPresenter.java, src/main/java/mat/client/shared/MessageDelegate.java, src/main/java/mat/client/shared/PasswordRules.java, src/main/java/mat/server/LoginServiceImpl.java, src/main/java/mat/server/MyAccountServiceImpl.java, src/main/java/mat/server/service/impl/UserServiceImpl.java, src/main/java/mat/shared/PasswordVerifier.java, src/test/java/mat/shared/PasswordVerifierTest.java
Removed run char and dictionary word requirements from passwords.
Password changed to 15 min chars 128 max chars.
Updated password requirements text.
Updated test cases for above changes.
Added time to TRANSACTION_AUDIT_LOG entry to stop the server error because its a non null field in the table.
=> Story MAT-523: https://jira.cms.gov/browse/MAT-523

src/main/java/liquibase/changelog.xml, src/main/java/liquibase/setAdminPasswordsAsTemp.xml
https://jira.cms.gov/browse/MAT-524
- Added script to set admin temp password to true
- Added script to changelog.xml
=> hotfix/MAT-524: Adding liquibase script to set admin passwords to temp.

src/main/java/mat/client/Login.java, src/main/java/mat/client/login/SecurityBannerModal.java
Added security banner after login. https://jira.cms.gov/browse/MAT-659
- Added a new modal class.
- Added the banner after login was verified as success in all login cases (normal, first time, etc).
=> Added security banner after login. 

src/main/java/mat/client/Login.java, src/main/java/mat/client/login/SecurityBannerModal.java
This change has already been made and QAed in master branch.
Story: https://jira.cms.gov/browse/MAT-659
=> Adding security banner to develop branch.

src/main/java/mat/client/shared/CQLLibraryResultTable.java, src/main/java/mat/model/cql/CQLLibraryDataSetObject.java
Reworked the code that handles selections in the Mat Library tab.
The checkboxes had strange behavior if you clicked two rows quickly. This code fixes that.
=> MAT-662: Fixed checkbox issues on the Library tab in MAT

src/main/java/mat/client/login/SecurityBannerModal.java
One line fix to fix a typo in the security banner.
=> Fixed typo in security banner html.

src/main/java/mat/client/login/SecurityBannerModal.java
Fixed typo in security banner master branch.
=> Fixed typo in security banner master branch.

src/main/java/mat/client/advancedsearch/AdvancedSearchPanel.java, src/main/java/mat/client/measure/ManageMeasurePresenter.java, src/main/java/mat/dao/clause/impl/CQLLibraryDAOImpl.java, src/main/java/mat/dao/clause/impl/MeasureDAOImpl.java, src/main/java/mat/shared/SearchModel.java
Adds model type filtering to the measure tab in MAT.
This already existed in the Library tab so the changes were very easy.
=> MAT-506: Added model type filtering to the Measure tab in MAT.

src/main/java/mat/client/Bonnie.java, src/main/java/mat/server/bonnie/BonnieServiceImpl.java, src/main/java/mat/server/bonnie/api/BonnieAPIv1.java
Added couple of logger.debug and logger.error statements to debug the mat bonnie integration issue
=> MAT-704 debug mat bonnie integration

src/main/java/mat/client/export/measure/ManageMeasureExportView.java, src/main/java/mat/dao/clause/impl/QDSAttributesDAOImpl.java, src/main/java/mat/hibernate/HibernateConf.java, src/main/java/mat/server/AdminServiceImpl.java, src/main/java/mat/server/Application.java, src/main/java/mat/server/BulkExportServlet.java, src/main/java/mat/server/CQLLibraryService.java, src/main/java/mat/server/ExportServlet.java, src/main/java/mat/server/HibernateStatisticsFilter.java, src/main/java/mat/server/MeasureLibraryServiceImpl.java, src/main/java/mat/server/MyAccountServiceImpl.java, src/main/java/mat/server/PopulationServiceImpl.java, src/main/java/mat/server/VSACApiServImpl.java, src/main/java/mat/server/bonnie/BonnieServiceImpl.java, src/main/java/mat/server/clause/QDSAttributesServiceImpl.java, src/main/java/mat/server/fhirvalidation/FhirValidationReportServlet.java, src/main/java/mat/server/hibernate/HibernateUserDetailService.java, src/main/java/mat/server/service/impl/CQLLibraryAuditServiceImpl.java, src/main/java/mat/server/service/impl/LoginCredentialServiceImpl.java, src/main/java/mat/server/service/impl/MeasureAuditServiceImpl.java, src/main/java/mat/server/service/impl/MeasureDetailsServiceImpl.java, src/main/java/mat/server/service/impl/MeasurePackageServiceImpl.java, src/main/java/mat/server/service/impl/PackagerServiceImpl.java, src/main/java/mat/server/service/impl/SecurityQuestionsServiceImpl.java, src/main/java/mat/server/service/impl/SimpleEMeasureServiceImpl.java, src/main/java/mat/server/service/impl/UserAuditServiceImpl.java, src/main/java/mat/server/service/impl/ZipPackager.java, war/WEB-INF/applicationContext-service.xml
Fixed MAT-146. What was going on was there were two spring beans and getBean was being called which threw an exception preventing cql exports. 
To fix this i went ahead and did some technical debt cleanup. I removed all the xml configured beans and did it all with annotations. After doing this I also had to go in and fix the places where the bean names were referenced.
=> Fixed MAT-146 + Technical Debt cleanup

src/main/java/mat/server/util/MeasureUtility.java, src/test/java/mat/server/util/MeasureUtilityTest.java
This is an existing functionality, the issue seems to be caused because of one of my previous commits. 
This commit doesn't address the bug identified by Chris. https://jira.cms.gov/browse/MAT-730. But this fix is necessary to work on the actual bug.
=> issue while replacing other Version of Include Libraries.

src/main/java/mat/client/login/SecurityBannerModal.java, src/main/java/mat/server/LoginServiceImpl.java
MAT-668 Security Banner changes & Build fix.
=> MAT-668 Security Banner changes & Build fix.

src/main/java/mat/client/login/SecurityBannerModal.java
Made the text a little larger and the dialog wider.
=> MAT-668 made Security Banner text a little larger and the dialog wider.

src/main/java/mat/client/login/SecurityBannerModal.java
Made text a big bigger and dialog wider.
=> MAT-668 Develop changes merged into master

src/main/java/mat/client/measure/service/CQLService.java, src/main/java/mat/server/CQLLibraryService.java, src/main/java/mat/server/CQLServiceImpl.java, src/main/java/mat/server/MeasureLibraryServiceImpl.java, src/main/java/mat/server/service/impl/MeasureCloningServiceImpl.java
Handled Cql validations for Functions, Definitions, Functions, Cql Library editor during a load of specific tab and also during the save of code.
=> Handled Cql validations

src/main/java/mat/client/cql/CQLLibrarySearchView.java, src/main/java/mat/client/shared/CQLibraryGridToolbar.java, src/main/java/mat/client/shared/MeasureLibraryGridToolbar.java, src/main/java/mat/client/shared/MostRecentCQLLibraryWidget.java, src/main/java/mat/dao/clause/impl/CQLLibraryDAOImpl.java, src/main/java/mat/model/cql/CQLLibraryDataSetObject.java, src/main/java/mat/model/cql/CQLLibraryShareDTO.java, src/main/java/mat/server/CQLLibraryService.java, src/main/java/mat/server/service/impl/MatContextServiceUtil.java, src/test/java/mat/client/shared/CQLibraryGridToolbarTest.java, src/test/java/mat/server/service/impl/MatContextServiceUtilTest.java
https://jira.cms.gov/browse/MAT-719
Add Convert to FHIR button in CQL Libraries page
=> MAT-719 convert library button

src/main/java/mat/server/service/impl/UserServiceImpl.java
[MAT-522] Fix hibernate lazy loading error (#91):
* Fixed hibernate lazy loading error when password history was being accessed from user entity outside of hibernate session. Replaced with call to DAO save.
* Fixed comments to describe updated day limits. Replaced on-demand import with individuals.
=> [Bugfix] Fix from develop for user password check lazy init error

uml/CQL Library Convert to FHIR.puml
=> Tech Spike - Determine how to store the FHIR library in the MAT

src/main/java/mat/cql/CqlToMatXml.java, src/test/resources/test-cql/convert-1.cql
Changed the library parsing to only check the first line from now on and no other lines.
=> feature/MAT-794 Fixed issue with CQL parsing where a "library " in a comment would triggering an error condition.

src/main/java/mat/cql/CqlStringUtils.java, src/main/java/mat/cql/CqlToMatXml.java, src/test/java/mat/cql/TestCqlStringUtils.java, src/test/java/mat/cql/TestCqlToMatXml.java, src/test/resources/test-cql/convert-1.cql
- Fixed issues with function arguments that look like this: b List<"Medication, Order"> ,c "C"
- Added code to remove all cql block comments and all line comments. (Duane wanted this)
- Added code to set attribute type on function arguments.
=> MAT-794 Fixed edge case CQL -> Mat XML conversion bugs

src/main/java/mat/cql/CqlStringUtils.java, src/main/java/mat/cql/CqlToMatXml.java, src/test/java/mat/cql/TestCqlStringUtils.java, src/test/java/mat/cql/TestCqlToMatXml.java, src/test/resources/test-cql/convert-1.cql
- Fixed issues with function arguments. Comma was being appended to type.
- ArgumentType is now the actual type. Before it was FHIR Datatype.
- Some code cleanup.
=> MAT-794 Issues with function arguments

src/main/java/mat/cql/CqlToMatXml.java, src/test/java/mat/cql/TestCqlToMatXml.java, src/test/resources/test-cql/convert-1.cql
MAT-794 Fixed issue with quoted type in arguments not stored off as quoted.
=> MAT-794 Fixed issue with quoted type in arguments not stored off as quoted.

src/main/java/mat/cql/CqlStringUtils.java, src/main/java/mat/cql/CqlToMatXml.java, src/test/java/mat/cql/TestCqlStringUtils.java, src/test/java/mat/cql/TestCqlToMatXml.java, src/test/resources/test-cql/convert-1.cql
Fixed issues with Tuple and List<Tuple> arguments in functions. 
Before the fix it was erroring out when converting cql -> mat xml.
=> MAT-799 Fixed issues with Tuple and List<Tuple> arguments in functions.

src/main/resources/templates/fhirvalidationreport/fhir_cql_conversion_errors.ftl, src/main/resources/templates/fhirvalidationreport/library_fhir_validation_errors.ftl, src/main/resources/templates/fhirvalidationreport/measure_fhir_validation_errors.ftl, src/main/resources/templates/fhirvalidationreport/qdm_cql_conversion_errors.ftl, src/main/resources/templates/fhirvalidationreport/valueset_fhir_validation_errors.ftl
Converting Severity to lower case and Capitalizing the first letter.
=> Consistent Case in Validation Report

src/main/resources/templates/fhirvalidationreport/validation_report_header.ftl
In the free-marker template, removed the following nodes
-  outcome
- header
=> MAT-792 refine freemarker template

src/main/java/mat/client/cqlworkspace/AbstractCQLWorkspacePresenter.java, src/main/java/mat/client/cqlworkspace/SharedCQLWorkspaceUtility.java, src/main/java/mat/cql/CqlParser.java, src/main/java/mat/server/CQLServiceImpl.java, src/main/java/mat/shared/SaveUpdateCQLResult.java
MAT-876 Fix error message if a lib version is in error or other CQLParser issue.
Also added some logging messages.
=> MAT-876 Fix error message if a lib version is in error or other CQLParser issue.

src/main/java/mat/client/harp/HarpUserVerificationPresenter.java, src/main/java/mat/client/harp/HarpUserVerificationView.java, src/main/java/mat/client/harp/NewUserRegistrationModal.java
=> Added New User Access page

src/main/java/mat/client/Mat.java, src/main/java/mat/client/harp/NewUserRegistrationModal.java, src/main/java/mat/client/login/service/LoginService.java, src/main/java/mat/client/login/service/LoginServiceAsync.java, src/main/java/mat/dao/UserDAO.java, src/main/java/mat/dao/impl/UserDAOImpl.java, src/main/java/mat/server/LoginServiceImpl.java, src/main/java/mat/server/service/impl/LoginCredentialServiceImpl.java, uml/HarpIntegration/existing_user_login_flow.puml
=> Replacing Email Id with Harp Id to identify users, and saving Email every-time user log in to MAT

src/main/java/mat/client/admin/ManageUsersDetailModel.java, src/main/java/mat/client/admin/ManageUsersDetailView.java, src/main/java/mat/client/admin/ManageUsersPresenter.java, src/main/java/mat/client/admin/service/AdminServiceAsync.java, src/main/java/mat/client/shared/MessageDelegate.java, src/main/java/mat/server/AdminServiceImpl.java, src/main/java/mat/server/service/impl/UserServiceImpl.java, src/main/java/mat/shared/AdminManageUserModelValidator.java, src/test/java/mat/shared/AdminManageUserModelValidatorTest.java
New user form requires a HARP ID
Existing user form - doesn't require HARP ID.
It's a PR for develop branch.
Master branch misses required db and harp changes yet
=> MAT-900 admin harp id new user

src/main/java/liquibase/addHarpIdColumn.xml, src/main/java/liquibase/changelog.xml, src/main/java/mat/dao/UserDAO.java, src/main/java/mat/dao/impl/UserDAOImpl.java, src/main/java/mat/model/User.java, src/main/java/mat/server/hibernate/HibernateUserDetailService.java, src/main/java/mat/server/model/MatUserDetails.java, src/main/java/mat/server/service/UserService.java, src/main/java/mat/server/service/impl/UserServiceImpl.java, src/main/java/mat/shared/HarpConstants.java
- Adding the HARP_ID field to the 5.8 database.
- Updating User Entity and DAO to accommodate new field.
- Initial (partial) add of service code for HARP integration.
=> MAT-880: Add HARP_ID field to 5.8 Database and update related entities and dao

war/js/HarpLogin.js, war/signInWidget/css/otka-theme.css
- fix for tokenManager not initializing.
- adding text to login widget to clarify use of HARP ID.
=> mat 887 uninitialized token manager

src/main/java/mat/client/Mat.java, src/main/java/mat/server/HarpServiceImpl.java
Re-adding `mainTabLayoutID`. Was lost while migrating the HARP integration from develop, which caused the "loading please wait" alert to fire on Mat load.
Removing commented code.
=> [MAT-880] Fixing alert on Mat load

pom.xml, src/main/java/liquibase/addNewPackagingColumns.1.2.xml, src/main/java/liquibase/changelog.xml, src/main/java/mat/model/clause/CQLLibraryExport.java, src/main/java/mat/model/clause/MeasureExport.java, src/main/java/mat/server/CQLLibraryService.java
- Changed JSON type over to long text. 
- Moved MS packaging calls until after the version is changed in the MAT db.
=> MAT-918: Standalone lib bug fixes.

src/main/java/mat/server/MeasureLibraryServiceImpl.java
Fixed a bug Rohit found where creating CQL_LIB when finalized date was null.
=> MAT-177 Fixed a bug Rohit found where creating CQL_LIB when finalized date was null.

src/main/java/mat/server/model/MatUserDetails.java
MAT-992 Enhance MAT Login when -  Inactive User Bug
=> MAT-992 Enhance MAT Login when -  Inactive User Bug

src/main/java/mat/client/measurepackage/MeasurePackagePresenter.java, src/main/java/mat/model/clause/MeasureExport.java, src/main/java/mat/server/ExportServlet.java, src/main/java/mat/server/humanreadable/HumanReadableGenerator.java, src/main/java/mat/server/service/impl/MeasurePackageServiceImpl.java, src/main/java/mat/server/service/impl/SimpleEMeasureServiceImpl.java, src/main/java/mat/server/service/impl/ZipPackager.java, src/main/java/mat/server/service/impl/ZipPackagerFactory.java, src/main/java/mat/shared/FileNameUtility.java
Navigation - Measure Composer / Measure Packager / Create Package and Export Button
=> Exporting FHIR bundle

src/main/java/liquibase/addNewPackagingColumns.1.7.xml, src/main/java/liquibase/changelog.xml, src/main/java/mat/model/clause/CQLLibraryExport.java, src/main/java/mat/model/clause/MeasureExport.java, src/main/java/mat/server/CQLLibraryService.java, src/main/java/mat/server/MeasureLibraryServiceImpl.java, src/main/java/mat/server/service/impl/ExportUtility.java, src/main/java/mat/server/service/impl/FhirMeasureRemoteCallImpl.java, src/main/java/mat/server/service/impl/MeasurePackageServiceImpl.java, src/main/java/mat/server/service/impl/SimpleEMeasureServiceImpl.java, src/main/java/mat/server/service/impl/ZipPackager.java
- Works with latest microservices changes.
- Json/XML is now pretty printed on "Package and Export"
- Changed from the store everything in the DB approach to generating from minimally required data to fix issues with MEASURE_EXPORT and CQL_LIBRARY_EXPORT being to large.
- Changed the artifacts for "Package and Export" now it just includes json no xml. XML will be available in export if needed.
=> MAT-177 Latest Packaging Microservices integration.

src/main/java/mat/server/humanreadable/cql/HumanReadableExpressionModel.java, src/main/java/mat/server/humanreadable/cql/HumanReadablePopulationCriteriaModel.java, src/main/java/mat/server/humanreadable/cql/HumanReadablePopulationModel.java, src/main/resources/templates/humanreadable/cql_expression.ftl, src/main/resources/templates/humanreadable/data_criteria_section.ftl, src/main/resources/templates/humanreadable/divider.ftl, src/main/resources/templates/humanreadable/expression.ftl, src/main/resources/templates/humanreadable/human_readable.ftl, src/main/resources/templates/humanreadable/population.ftl, src/main/resources/templates/humanreadable/population_criteria.ftl, src/main/resources/templates/humanreadable/population_criteria_section.ftl, src/main/resources/templates/humanreadable/population_human_readable.ftl, src/main/resources/templates/humanreadable/terminology_section.ftl
- Fixed ids that contained spaces.
- Fixed other validation issues in the html.
=> MAT-177 Human readable changes:

src/main/java/liquibase/changelog.xml
Removed old columns and changed order scripts are executed.
=> MAT-1105 Fixed liquabase issues running older scripts.

src/main/java/mat/server/service/impl/ExportUtility.java, src/main/java/mat/server/service/impl/ZipPackager.java, src/main/java/mat/shared/FileNameUtility.java
Changed artifact names so they are easier to read. Only the dir includes name/version now.
=> MAT-1105 Added measure bundle

src/main/java/mat/server/CQLLibraryService.java, src/main/java/mat/server/util/QDMUtil.java
FHIR Version is not being updated in DB when creating a new Library, So causing the issue with searching included libraries.
=> Fixed issue with searching Included libraries.

src/main/java/liquibase/changelog.xml, src/test/java/mat/server/service/fhirvalidationreport/CqlLibraryValidationReportImplTest.java, src/test/java/mat/server/service/fhirvalidationreport/MeasureValidationReportImplTest.java, src/test/java/tools/GenerateCommonFhirLibSql.java
They broke when we switch apis. Created a story to bring them back again when we have time.
=> MAT-1105 Commented out report validation test cases. Updated global common libs. Added tool for global common libs.

src/main/java/mat/client/CqlLibraryPresenter.java, src/main/java/mat/client/measure/ManageMeasurePresenter.java, src/main/java/mat/client/measure/service/FhirConvertResultResponse.java, src/main/java/mat/server/CQLLibraryService.java, src/main/java/mat/server/service/impl/FhirCqlLibraryServiceImpl.java, src/main/java/mat/server/service/impl/FhirMeasureServiceImpl.java, src/test/java/mat/server/service/impl/FhirMeasureServiceImplTest.java
It was an issue with both libraries and measures.
=> MAT-1164 Fixed conversion report being different than fhir validation report.

src/main/java/mat/client/measure/measuredetails/observers/GeneralInformationObserver.java, src/main/java/mat/client/measure/measuredetails/views/GeneralInformationView.java, src/main/java/mat/server/MeasureLibraryServiceImpl.java, src/main/java/mat/server/util/ManageMeasureDetailModelConversions.java
Saving Measurement Period for FHIR. The default period is the next Calender year (generated during new FHIR measure creation).
=> Measurement Period for FHIR

src/main/java/mat/server/humanreadable/HumanReadableGenerator.java, src/main/java/mat/server/service/impl/FhirMeasureServiceImpl.java, src/main/java/mat/server/service/impl/ZipPackager.java
- fixed conversions 
- added lookups based on names for Supplemental and Risk elements. Before it was using IDs.
=> MAT-1180 Latest code system fixes.

src/main/java/liquibase/addSevereErrorCqlColumn.xml, src/main/java/liquibase/changelog.xml, src/main/java/mat/client/measure/service/CQLService.java, src/main/java/mat/model/clause/CQLLibrary.java, src/main/java/mat/model/clause/MeasureXML.java, src/main/java/mat/server/CQLLibraryService.java, src/main/java/mat/server/CQLServiceImpl.java, src/main/java/mat/server/MeasureLibraryServiceImpl.java, src/main/java/mat/server/service/impl/MeasureCloningServiceImpl.java, src/main/java/mat/shared/SaveUpdateCQLResult.java
=> MAT-1227 Added saving on severe errors.

src/main/java/mat/server/ExportServlet.java, src/main/java/mat/server/service/SimpleEMeasureService.java, src/main/java/mat/server/service/impl/SimpleEMeasureServiceImpl.java, src/main/java/mat/server/service/impl/ZipPackager.java
Fhir JSON is being open/saved when exporting instead of Json from Database.
=> Fhir JSON is being open/saved when exporting

src/main/java/mat/server/service/impl/ZipPackager.java
=> Added Measure xml bundle to export Zip folder

src/main/java/liquibase/changelog.xml, src/main/java/mat/client/cqlworkspace/AbstractCQLWorkspacePresenter.java, src/main/java/mat/client/cqlworkspace/SharedCQLWorkspaceUtility.java, src/main/java/mat/server/CQLLibraryService.java, src/main/java/mat/server/CQLServiceImpl.java, src/main/java/mat/server/MeasureLibraryServiceImpl.java, src/main/java/mat/server/service/cql/CqlValidationResultBuilder.java
- Also added error message when saving with severe errors. Added code to not create a CQLLibraryExport if a row already exists.
=> MAT-1288 measure-lib version now matches measure version

src/main/java/mat/client/measure/ManageMeasurePresenter.java, src/main/java/mat/client/shared/MeasureLibraryGridToolbar.java, src/main/java/mat/client/shared/MeasureLibraryResultTable.java, src/main/java/mat/server/service/impl/SimpleEMeasureServiceImpl.java, src/main/java/mat/server/service/impl/ZipPackager.java
=> Bulk Export changes

src/main/java/mat/model/clause/MeasureExport.java, src/main/java/mat/server/hqmf/qdm/HQMFGenerator.java, src/main/java/mat/server/humanreadable/HumanReadableGenerator.java, src/main/java/mat/server/humanreadable/cql/CQLHumanReadableGenerator.java, src/main/java/mat/server/humanreadable/cql/HumanReadableCodeModel.java, src/main/java/mat/server/humanreadable/cql/HumanReadableValuesetModel.java, src/main/java/mat/server/humanreadable/qdm/HQMFHumanReadableGenerator.java, src/main/java/mat/server/service/FhirMeasureRemoteCall.java, src/main/java/mat/server/service/cql/HumanReadableArtifacts.java, src/main/java/mat/server/service/impl/FhirMeasureRemoteCallImpl.java, src/main/resources/templates/humanreadable/data_criteria_section.ftl, src/main/resources/templates/humanreadable/table_of_contents.ftl
Missing functions, defines, term codes, term value sets, data requirements for FHIR.
Also updated HR to use FHIR Data Requirements for FHIR instead of QDM Data Elements.
=> MAT-1302 Adding missing stuff to HR for FHIR. 

src/main/java/mat/client/cqlworkspace/generalinformation/StandaloneCQLGeneralInformationView.java, src/main/java/mat/server/CQLLibraryService.java
- Also added code to copy over description, steward, and experimental when drafting libs.
=> MAT-1556 Fixed issue when searching for included lib.

src/main/java/liquibase/changelog.xml, src/main/java/mat/server/service/impl/FhirMeasureServiceImpl.java
It was picking the first non-null lib in the results. Changed it to also search for a name matching the measure lib name.
=> Bugfix The wrong cql was being selected during conversion. 

src/main/java/mat/server/clause/MeasureCloningRemoteServiceImpl.java, src/main/java/mat/server/service/MeasureCloningService.java, src/main/java/mat/server/service/impl/FhirMeasureServiceImpl.java, src/main/java/mat/server/service/impl/MeasureCloningServiceImpl.java, src/main/java/mat/server/util/ManageMeasureDetailModelConversions.java, src/test/java/mat/server/service/impl/FhirMeasureServiceImplTest.java
=> MAT-1550 During conversion if the Reference type is UNKNOWN it is defaulted to CITATION.

Dockerfile
This'll fix the bonnie mat integration issue
=> add sb intermediate cert to ca

.github/dependabot.yml
Creating Dependabot.yml for automated PRs MAT-2216
=> MAT-2216 | Create dependabot.yml 

src/main/java/mat/client/measure/measuredetails/views/DescriptionView.java, src/main/java/mat/client/measure/measuredetails/views/GeneralInformationView.java, src/main/java/mat/client/measure/measuredetails/views/MeasureStewardView.java, src/main/java/mat/client/measure/measuredetails/views/MeasureTypeView.java, src/main/java/mat/client/validator/ErrorHandler.java
Also added table support to ErrorHandler.
=> MAT-2221 Completed adding required fields to measure detail tabs.

src/main/java/mat/client/measure/measuredetails/views/DescriptionView.java, src/main/java/mat/client/measure/measuredetails/views/MeasureTypeView.java
Measure details description and measure type were not working correctly.
=> BUGFIX Fixed issue Kathy found where with measure details.

src/main/java/mat/client/populationworkspace/CQLPopulationWorkSpacePresenter.java, src/main/java/mat/server/service/cql/FhirCqlParserService.java, src/main/java/mat/server/service/impl/MeasurePackageServiceImpl.java
Also added busy indicator on save for populations.
=> BUGFIX Measure xml/json didn't have HR first time through.

uml/HarpIntegration/NewHarpLoginFlow, uml/HarpIntegration/OldHarpLoginFlow.puml
Existing flow (Everything is done on the client side in MAT)
New flow (Everything is done on the server side now)
=> MAT-1987 Tech spike to fix privilege escalation bug.

war/Bonnie.html, war/Mat.html, war/signInWidget/js/okta-sign-in.js
Also added missing termsAndConditions init validation.
=> BUGFIX Attempt to fix querySelectorAll issue in IE11. 

.github/PULL_REQUEST_TEMPLATE.md
Example of how the template will appear on future PRs once this template is merged.
=> Starter PR Template

src/main/java/mat/server/humanreadable/HumanReadableGenerator.java
Reverted the changes made for generating cqlModel from simpleXML to Measure XML.
https://jira.cms.gov/browse/MAT-2586
=> Reverted HR changes for Missing Definitions

pom.xml, src/main/resources/MAT.properties, super-dev-mode/pom.xml
Upping the MAT version to 6.04 for the 02/11/2021 release.
=> Bumping version for release

src/main/java/mat/server/humanreadable/HumanReadableGenerator.java, src/main/java/mat/server/humanreadable/helper/DataRequirementsNoValueSetFilter.java
=> Removed filter for for value sets

mat-cypress/Readme.md, mat-cypress/cypress/integration/cql-library/cqlLibrarySearchShared.spec.js, mat-cypress/cypress/integration/matLogin.spec.js, mat-cypress/cypress/support/commands.js, mat-cypress/cypress/support/domain/pageElements/LogoutElement.js, mat-cypress/cypress/support/domain/pageElements/UmlsElement.js, mat-cypress/cypress/support/helpers.js, mat-cypress/cypress/support/loginCommands.js, mat-cypress/package-lock.json, mat-cypress/package.json
=> Added readme and started PageObjects

src/test/java/mat/shared/validator/measure/CommonMeasureValidatorTest.java
=> Update the unit test with latest text constants

mat-cypress/cypress/integration/measures/CQLWorkspaceDefinition.spec.js, mat-cypress/cypress/support/domain/pageDialogs/InsertItemCqlEditorDialog.js, mat-cypress/cypress/support/domain/pageDialogs/InsertOptionsForAttributesDialog.js, mat-cypress/cypress/support/domain/pageObjects/CqlWorkspaceDefinitionPage.js, mat-cypress/cypress/support/domain/pageObjects/CqlWorkspaceGeneralInformationPage.js, mat-cypress/cypress/support/domain/pageObjects/MeasureComposerPage.js, mat-cypress/cypress/support/domain/pageObjects/MeasureLibPage.js, mat-cypress/cypress/support/measureCommands.js, src/main/java/liquibase/QDM_5_6_Updates_v4.xml, src/main/java/liquibase/changelog.xml
Added new liqui base script and wrote cypress check to verify a new attribute is displayed
=> Removed and added new attributes

src/main/java/mat/client/measure/ManageMeasurePresenter.java, src/main/java/mat/client/measure/measuredetails/observers/GeneralInformationObserver.java, src/main/java/mat/client/shared/MatContext.java
MAT-2709
- The continuous variable measures are changed to be patient-based.
- When creating a new measure, the patient-based dropdown used to have only "NO" for the continuous variable measure.
- Now the changes have been made for CV measures to be patient-based.
- The same works for the patient-based input field on the Measure General information details page.
https://jira.cms.gov/browse/MAT-2709
=> Changed continuous variables measures to be patient based.

src/main/java/mat/server/CQLServiceImpl.java, src/main/java/mat/server/MeasureLibraryServiceImpl.java, src/main/java/mat/server/VSACAPIServiceImpl.java, src/main/java/mat/server/VSACApiServImpl.java
MAT-2507
For a specific Valueset "COVID_19 (Tests for SARS_CoV_2 Antigen)" OID: 2.16.840.1.113762.1.4.1146.1158.
an illegal character is being returned by VSAC. So in this case nbsp is replaced by regular space.
[https://jira.cms.gov/browse/MAT-2507](https://jira.cms.gov/browse/MAT-2507)
=> Replaced illegal unicode '\u00A0' with a regular space

mat-cypress/cypress/integration/cql-library/conversion/SuccessfulCqlLibraryConversion.spec.js, src/main/java/mat/shared/measure/measuredetails/validate/GeneralInformationValidator.java, src/main/java/mat/shared/validator/measure/CommonMeasureValidator.java, src/main/java/mat/shared/validator/measure/ManageMeasureModelValidator.java
MAT-2708
I found a bug in one of my older stories, fixed it. 
On the Measure general information page, upon save a validation is performed to validate the relation between patient-based and measure scoring. Since CV measures can be patient-based (changes made in MAT-2708). We need to remove this validation for QDM measures. 
https://jira.cms.gov/browse/MAT-2708
=> fixed few bugs in MAT-2708

src/main/java/mat/server/CQLServiceImpl.java, src/main/java/mat/server/MeasureLibraryServiceImpl.java
MAT-2507: Replace NBSP in FHIR Measure CQL
QDM artifacts do not seem to be impacted by NBSP in CQL, whereas FHIR measures have odd character replacement for NBSPs in their export artifacts.
Until this charset mismatch is resolved, replace instances of NBSP with a normal space in FHIR measure CQL.
[MAT-2507](https://jira.cms.gov/browse/MAT-2507)
=> [MAT-2507] Restrict NBSP replacement in CQL to FHIR only

src/main/java/mat/server/util/fhirxmlclean/CodeCleaner.java, src/main/java/mat/server/util/fhirxmlclean/FhirCleanerBase.java, src/main/java/mat/server/util/fhirxmlclean/LibraryCleaner.java, src/main/java/mat/server/util/fhirxmlclean/ValueSetCleaner.java, src/main/java/mat/server/util/fhirxmlclean/XmlUnusedFhirCleaner.java, src/main/java/mat/shared/SaveUpdateCQLResult.java, src/test/java/mat/server/util/fhirxmlclean/CodeCleanerTest.java, src/test/java/mat/server/util/fhirxmlclean/LibraryCleanerTest.java, src/test/java/mat/server/util/fhirxmlclean/ValueSetCleanerTest.java
Changes as per Codacy issues
[https://app.codacy.com/gh/MeasureAuthoringTool/MeasureAuthoringTool/pullRequest?prid=7205190&bid=22935313](Codacy)
=> Cleared Codacy issues

src/main/java/mat/server/util/fhirxmlclean/XmlUnusedFhirCleaner.java, src/test/java/mat/server/util/fhirxmlclean/CodeCleanerTest.java, src/test/java/mat/server/util/fhirxmlclean/LibraryCleanerTest.java, src/test/java/mat/server/util/fhirxmlclean/ValueSetCleanerTest.java, src/test/java/mat/server/util/fhirxmlclean/XmlUnusedFhirCleanerTest.java
=> Codacy fixes

pom.xml, src/test/java/mat/server/service/impl/MeasurePackageServiceImplTest.java, src/test/java/mat/server/util/fhirxmlclean/CodeCleanerTest.java
=> fixed snyk issues and MeasurePackageServiceImplTest

src/main/java/edu/ycp/cs/dh/acegwt/public/ace/mode-cql.js
Highlight the new QDM 5.6 Attributes in the CQL Library Editor
The ACE Editor identifies constants to highlight based on language specific javascript files.
Add the two new 5.6 Attributes to the cql language file:
- class
- interpretation
[MAT-2773](https://jira.cms.gov/browse/MAT-2773)
=> [MAT-2773] Add new QDM 5.6 Attributes to ACE Editor's constants list

.github/workflows/maven.yml
=> Cache maven dependencies for GH build action

src/main/java/liquibase/QDM_5_6_DataType_Update_v2.xml, src/main/java/liquibase/changelog.xml, src/main/resources/SimplifiedAttributePatterns.xml
MAT-2410
- Added new Modes 'class' and 'interpretation'.
- Removed DataType "Device, Not Applied" and its associated attributes.
[https://jira.cms.gov/browse/MAT-2410](MAT-2410)
=> Removed Device Not Applied DataType, Added new Modes

pom.xml, src/main/java/edu/ycp/cs/dh/acegwt/public/ace/mode-cql.js, src/test/java/mat/server/cqlparser/ReverseEngineerListenerTest.java
MAT-2773: Color code QDM 5.6 Entity and Datatype attributes
- Bump jackson-databind and jackson-core
- Color code QDM 5.6 Entity Attribute locationType in CQL Editor
- Refactor large unit test into smaller ones
=> Color code locationType Entity Attribute in CQL Editor

pom.xml
Replacing the cqframework snapshot with the full release version.
=> Bump cqframework to 1.5.3

.github/PULL_REQUEST_TEMPLATE.md, pmd.xml, src/main/java/mat/server/humanreadable/HumanReadableGenerator.java, src/main/java/mat/server/humanreadable/cql/HumanReadablePopulationCriteriaModel.java, src/main/resources/templates/humanreadable/population_criteria.ftl, src/main/resources/templates/humanreadable/population_criteria_section.ftl
The Score Unit value is an optional value set on the Measure Packager to one or more Package/Measure Groups.
Each Score Unit is persisted in the Measure XML at the Measure Group level at `measure/measureGrouping/group/@ucum`. Updating the HumanReadableGenerator to retrieve these values and add them to `HumanReadableModel` object that is passed into the Freemarker template engine to generate the QDM Human Readable.
Conditional checks added to the Freemarker population criteria templates (separate templates for single group and multiple groups) to check for Score Unit and, when present, display under the relevant Population Criteria section.
Also, rephrase Title and Screenshot requests in PR template to emphasize the jira number should go in the title field.
Removed whitespace between the …
=> [MAT-2697] Add Score Unit (Target Unit) to QDM Human Readable

pmd.xml, src/main/java/mat/dao/clause/MeasureExportDAO.java, src/main/java/mat/dao/clause/impl/MeasureExportDAOImpl.java, src/main/java/mat/server/humanreadable/HumanReadableGenerator.java, src/main/java/mat/server/service/impl/MeasurePackageServiceImpl.java, src/main/java/mat/server/service/impl/SimpleEMeasureServiceImpl.java
- Add save and flush for measure export
- Hack to handle circular dependency between HAPI and the Human Readable
[MAT-2825](https://jira.cms.gov/browse/MAT-2825)
=> [MAT-2825] Sync up Human Readable and FHIR Measure's text element

src/main/java/mat/client/shared/MeasureLibraryResultTable.java, src/main/java/mat/model/clause/Measure.java, src/main/java/mat/server/ExportServlet.java, src/main/java/mat/server/service/impl/SimpleEMeasureServiceImpl.java, src/main/java/mat/server/service/impl/ZipPackager.java, src/main/java/mat/shared/FileNameUtility.java
[MAT-2985](https://jira.cms.gov/browse/MAT-2985)
=> Updated FHIR Bulk export fileNames.

war/Login.html
- update terms of use link in footer
- update 508 link in login footer
[MAT-2986](https://jira.cms.gov/browse/MAT-2986)
=> [MAT-2986] Update Links to External Sites

src/main/java/mat/client/measure/ManageMeasurePresenter.java
Resetting patient-based indicator to default upon model selection. 
[MAT-3001](https://jira.cms.gov/browse/MAT-3001)
=> Resetting patient based indicator to default upon modelSelection

src/main/java/mat/client/cqlworkspace/AbstractCQLWorkspacePresenter.java, src/main/java/mat/client/cqlworkspace/CQLMeasureWorkSpacePresenter.java, src/main/java/mat/client/cqlworkspace/CQLStandaloneWorkSpacePresenter.java, src/main/java/mat/client/cqlworkspace/EditIncludedLibraryDialogBox.java, src/main/java/mat/dao/clause/impl/CQLLibraryDAOImpl.java
- Correct spelling in method signatures
- Update replacement Library Query
- Set type in callback
=> Check FHIR Version to identify Replacement Libraries

src/main/java/mat/client/measure/ManageMeasurePresenter.java, src/main/java/mat/server/service/impl/MeasureCloningServiceImpl.java
- Rename local variables to be more generic
- Reduce Patient-based options when Model is FHIR
=> Include Yes and No patient-based options for draft and cloned QDM measures

src/main/java/mat/client/admin/ManageUsersDetailModel.java, src/main/java/mat/server/AdminServiceImpl.java
- INFO log user activation, revocation, and role change.
- Remove sys out logging.
- Log using internal User ID to avoid PII leak.
=> Log User Management Events

war/WEB-INF/web.xml
Remove Commented out "Secure Flag and Http-Only" for JSessionID in web.xml
[MAT-3039](https://jira.cms.gov/browse/MAT-3039)
=> Fix Commented out Secure Flag

src/main/java/mat/client/cqlworkspace/CQLMeasureWorkSpacePresenter.java
Removed check for the emptiness of searchField, as it is handled by blur handler, Can't test it in my local, So would like to test in dev. 
[MAT-3084](https://jira.cms.gov/browse/MAT-3084)
=> unable to add included library because of inline error check

src/main/java/mat/server/CQLServiceImpl.java
Fixed displaying return type for definitions in this [PR](https://github.com/MeasureAuthoringTool/MeasureAuthoringTool/pull/708.) 
Although I missed doing the same for functions UI. 
[MAT-3113](https://jira.cms.gov/browse/MAT-3113)
=> fixed return type for functions UI

war/Bonnie.html, war/HarpSupport.html
=> Update the CSP to permit the GWT modules to load

src/main/java/mat/client/CqlLibraryPresenter.java, src/main/java/mat/client/Mat.java, src/main/java/mat/client/cql/NewLibraryView.java, src/main/java/mat/client/measure/AbstractNewMeasureView.java, src/main/java/mat/client/measure/ManageMeasurePresenter.java, src/main/java/mat/client/shared/MatContext.java, src/main/resources/MAT.properties
Remove checks for any FHIR flag, global or individual. 
Another PR will remove the Admin UI flag control and the flag entry from the feature flag table.
Minor updates:
- Updates footer URLs on the HARP support page.
- Logs the harp session revocation event at info, instead of severe, level.
=> Remove FHIR Flag checks

src/main/java/mat/client/cqlworkspace/CQLMeasureWorkSpacePresenter.java
Changes to load Cql information, irrespective of errors in Cql. 
Although a check is already in place to see, if it there are SEVERE errors, if yes, then the left nav bar is disabled. 
[MAT-3264](https://jira.cms.gov/browse/MAT-3264)
=> Displaying Cql General information for SEVERE errors.

src/main/java/mat/server/service/impl/xsl/qdm_v5_6_measure_details.xsl
- Remove unused xsl variable
- Use the file naming format from export files in the HQMF's relatedDocuments section
[MAT-3714](https://jira.cms.gov/browse/MAT-3714)
=> [MAT-3714] Match values in HQMF relatedDocument with Export file names

src/main/java/mat/server/service/impl/xsl/qdm_v5_6_measure_details.xsl
Was using the Measure Name and not the Measure's Abbreviated title like the file name utility.
- Abbreviated Title is pulled from the SimpleXML's ShortTitle element.
=> Use the Measure Abbr Title in HQMF relatedDocument URLs

src/main/java/mat/server/service/impl/xsl/qdm_v5_6_measure_details.xsl
=> Use current file name formatting in HQMF relatedDocument URLs for included libraries

pom.xml
=> Revert mysql-connector version to 8.0.22 to retain compatibility with current liquibase version

src/main/java/mat/client/export/measure/ManageMeasureExportPresenter.java, src/main/java/mat/client/export/measure/ManageMeasureExportView.java
=> Updated success and error text

src/main/java/mat/vsac/VsacService.java
Per the [UMLS Authn instructions](https://documentation.uts.nlm.nih.gov/rest/authentication.html), the UMLS API Key should be passed in the request body, not as a query parameter.
Secondary: Corrected latest profile URL.
[MAT-4235](https://jira.cms.gov/browse/MAT-4235)
=> Pass UMLS API Key in request body

pom.xml, super-dev-mode/pom.xml
Non-breaking dependency updates to reduce vulns.
=> Bump versions for spring boot parent and jackson

src/main/resources/CQLXmlTemplate.fhir4.xml
https://jira.cms.gov/browse/MAT-4460
- Updated the CQL template with the latest versions of FHIRHelpers & MATGlobalCommonFunctionsFHIR4 for new FHIR measures.
- Updated the CQL template with the latest version of FHIRHelpers for new Stand alone FHIR measures.
=> Bump versions of default included libraries in Cql template

src/main/resources/CQLXmlTemplate.fhir4.xml
=> Updated SDE version for new measures

src/main/java/mat/server/CQLServiceImpl.java
=> Fixed the performance issue after adding new SDE to measure template
