MeasureAuthoringTool/MeasureAuthoringTool

README.md

These are instructions for developers to install and configure git secrets within their local development environment. Every developer should do this to help us catch potential secrets on commit to prevent them from being leaked before they are pushed to the code base.

Added instructions for developers to setup git-secrets pre-commit 

---

pom.xml

Just updating the minor versions of spring and spring security. Also updated dependencies to use a constant for easier upgrading in the future

Upgrading spring and spring security versions to address CVE-2019-3795

---

src/main/java/mat/client/cql/CQLLibrarySearchView.java
src/main/java/mat/client/shared/CQLLibraryResultTable.java
src/main/java/mat/model/cql/CQLLibraryDataSetObject.java

Differentiated Single Click and Double Click using SystemTime with 500ms as ideal threshold for consecutive clicks. 
'onBrowserEvent' is performed on a column instead of a row. So it is added for LibraryName Column, Version Column and Model Type Column. Hasn't implemented on other columns since they will be removed in MAT 63 & 68.
Note: removed the unwanted lines of code and previous implementations/ideas.

MAT 62 - 67 Revised with Single Click event

---

lgtm.yml

Remove the lines that skip unit tests for LGTM so they are accounted for during a build.
There is a desire to include unit test as part of the build criteria in the SAST process when LGTM builds the code. This commit modifies the lgtm.yml to not skip unit tests. While LGTM's focus is primarily security analysis, this change allows us to include successful unit tests as part as our successful build criteria which factors into our code quality over all.
This will also mean that breaking unit tests on a PR will not build successfully in LGTM. The assumed goal is that a PR should not break unit tests in any case, and if it does, it should be fixed. That said, this is an assumed case and as such should be taken into consideration during review.
Screenshot showing successful test build with new …

Remove the lines that skip unit tests for LGTM 

---

src/main/java/mat/client/CqlComposerPresenter.java
src/main/java/mat/client/MeasureComposerPresenter.java
src/main/java/mat/client/cqlworkspace/CQLMeasureWorkSpacePresenter.java
src/main/java/mat/client/cqlworkspace/CQLStandaloneWorkSpacePresenter.java
src/main/java/mat/client/shared/CQLLibraryResultTable.java
src/main/java/mat/client/shared/MeasureLibraryResultTable.java
src/main/java/mat/shared/model/util/MeasureDetailsUtil.java
src/test/java/mat/client/CqlComposerPresenterTest.java
src/test/java/mat/client/MeasureComposerPresenterTest.java
src/test/java/mat/shared/model/util/MeasureDetailsUtilTest.java

Acceptance Criteria:
1. Both measure library grids model columns reflect the new verbiage
2. Both CQL library grids model columns reflect the new verbiage
3. The measure CQL Workspace General Information page reflects the new verbiage
4. The CQL Composer General Information page reflects the new verbiage
5. The verbiage above the subtabs reflects the new model text
6. The column header caption is Models rather than Model
7. What currently displays as Pre-CQL will be displayed as QDM / QDM
8. What currently displays as QDM will be displayed as QDM / CQL
9. What currently displays as FHIR will be displayed as FHIR / CQL

Updated Model Type Display Name with new Verbiage

---

src/main/java/mat/client/measure/AbstractNewMeasureView.java

Acceptance Criteria:
- The FhirAdd feature flag is currently off in Dev and the sandbox environment. When we begin the work that allows the user to add a new FHIR measure, the flag will be on in Dev.
- When the flag is off, when the user creates a new measure the model type on the Create New Measure page is set to QDM and disabled.
- When the flag is on, when the user creates a new measure the model type on the Create New Measure page is defaulted to FHIR and the user can choose either FHIR or QDM.

Implemented FhirAdd Feature Flag

---

src/main/java/mat/server/service/jobs/CheckUserChangePasswordLimit.java
src/main/java/mat/server/service/jobs/CheckUserLastLoginTask.java
src/main/resources/MAT.properties
src/main/resources/templates/mail/mail_expiry_template.ftl
src/main/resources/templates/mail/mail_warning_template.ftl

https://jira.cms.gov/browse/MAT-522
- Updated password expiration day limit to 50 days with warning email occurring at 35 days.
- Updated account inactivation day limit to 60 days with warning email occurring at 30 days.
- Changed day counts in email templates and code comments.

MAT-522: Automated Password and User Activity Evaluation

---

src/main/java/mat/server/service/impl/UserServiceImpl.java
src/main/java/mat/server/service/jobs/CheckUserChangePasswordLimit.java

Password expiration emails stopped working in MATDEV around May 2019 due to a Hibernate lazy loading error when the check attempted to save the password history preventing the check from finishing.
- Error caused by service attempting to access the password history collection from a user entity outside of a hibernate session.
- Replaced call to access collection with PasswordHistoryDAO save.
Missed some comments describing day limits in original PR, fixing them error.

[MAT-522] Fix hibernate lazy loading error

---

src/main/java/liquibase/addFhirBonnieFeatureFlag.xml
src/main/java/liquibase/changelog.xml
src/main/java/mat/client/export/ManageExportPresenter.java
src/main/java/mat/client/export/ManageExportView.java
src/main/java/mat/client/measurepackage/MeasurePackagePresenter.java
src/main/java/mat/client/util/FeatureFlagConstant.java
src/main/java/mat/dao/impl/FeatureFlagDAOImpl.java

- Added FhirBonnie feature flag. Turned off for DEV and prod.
- "Package and Upload to Bonnie" will be disabled for FHIR measures when the FhirBonnie feature flag is off.
- "Upload to Bonnie" link in the Export page is hidden for FHIR measures when the FhirBonnie feature flag is off.

[MAT-650] disable bonnie integration

---

src/main/java/mat/dao/clause/impl/MeasureDAOImpl.java

MAT-506 Changed the dao to only do the measure set search when ModelType is ALL.
For FHIR,QDM/CQL,QDM.QDM the family search or measure set search won't be preformed.

MAT-506 Fixed measure search by model type.

---

src/main/java/mat/client/measure/AbstractNewMeasureView.java
src/main/java/mat/client/measure/NewCompositeMeasureView.java

- This is not behind a feature flag. Composite FHIR measures are turned off until the standards are agreed upon.
- In the Create New Composite Measure, the Model radio button is set to QDM and is disabled.

Limiting the creation of new composite measures to QDM

---

src/main/java/mat/server/CQLUtilityClass.java
src/main/java/mat/server/util/CQLUtil.java
src/main/java/mat/server/util/MeasureUtility.java
src/test/java/mat/server/util/MeasureUtilityTest.java

Solved the actual bug raised by Chris, But because of mismatch in formatting, MAT is unable to identify actual Includes libraries with similar versions. Therefore making the formatting unique.

Couldn't find includes library because of version mismatch.

---

src/main/java/mat/cql/CqlStringUtils.java
src/main/java/mat/cql/CqlToMatXml.java
src/main/java/mat/cql/ParseResult.java
src/test/java/mat/cql/TestCqlStringUtils.java
src/test/java/mat/cql/TestCqlToMatXml.java
src/test/resources/test-cql/convert-1.cql

Fixed issues when parsing function arguments that contained qdmTypes that are string literals with commas in them.
Fixed issues handling multiple function args.
Fixed issues where quoted string literals in cql that had escaped quotes \" would fail. e.g. "blah\"blah"
Added support to catch escaped tics also in ticed literals. e.g. 'blah\'bhah'
Refactored a string utils class out of CqlToMatXML so the utility methods are easy to test.
Added test cases.

MAT-794 Fixing issues with function arguments and escaped quotes in cql parsing.

---

src/main/java/mat/server/MeasureLibraryServiceImpl.java

When a new measure was being created, it was causing an error in the `mat.fhir.services` micro-service as it was expecting a `measure-details` row for each `measure` record
modify the logic for the `saveNewMeasure` to ensure that it creates a corresponding row in the `measure_details` table during the creation of a new `measure`.

MAT-820 bug fix during create new Measure

---

src/main/java/mat/dao/clause/impl/MeasureDAOImpl.java

When attempting to create a composite measure, in the second screen, one has to search for existing (component) measures that would need to be added to create the composite measure. Currently, the search is failing due to `measureSetIds` being null or empty while doing a native query which uses the `IN` clause.
Added a pre-condition check to the `measureSetIds` parameter to make sure it is not null or empty before executing the query.
https://jira.cms.gov/browse/MAT-860

MAT-860 search component measure failing while creating a composite measure

---

uml/MAT-831-get_codesystem_mappings.puml
uml/MAT-831-map-codesystem-oid-to-url.puml
uml/MAT-831-map-codesystem-url-to-oid.puml

We are using a google sheet to store the oid -> url mappings:
https://docs.google.com/spreadsheets/d/15YvJbG3LsyqqN4ZIgRd88fgScbE95eK6fUilwHRw0Z0/edit#gid=0
Rob is going to fill in the TBD OIDs. These are OIDs that can't be found in FHIR 4.0.1.
**Fetching Spreadsheet data from Mat:**
**OID(QDM) to URL(FHIR)**
**URL(FHIR) to OID(QDM)**

MAT-831 Tech spike to determine how to handle codesystems in fhir '4.0.1'

---

src/main/java/mat/Mat.gwt.xml
src/main/java/mat/client/MainLayout.java
src/main/java/mat/client/Mat.java
src/main/java/mat/client/util/ClientConstants.java
src/main/java/mat/server/Application.java
src/main/java/mat/server/PreventCachingFilter.java
src/main/java/mat/server/service/impl/LoginCredentialServiceImpl.java
war/HarpLogin.js
war/Mat.html

**Issue:** The MAT Logout operations and the Okta logout API were attempting to re-direct to the login page, creating a race condition on whether or not the Okta logout would complete before being cancelled by the redirect.
**Solution:** Update the logout flow to wait to redirect until all logout operations are complete and move the Okta logout call to the end to ensure it's not being impacted.
1. Revoke Access Token.
2. Complete MAT logout operations.
3. Destroy browser Okta session by calling Otka logout endpoint.
4. Wait 1 second, then re-direct to login page.
Previously, there step 2 & 3 were swapped and there was no wait before the re-direct.

[MAT-898] Updated logout flow to prevent Okta session retension

---

src/main/java/mat/client/Mat.java

The Loading bar was started before the HARP-MAT account link verification, causing the bar to remain in the header if the user needed to link their accounts and remain during account verification. Adjusted its timing to start after account verification.

Prevent Loading bar from stalling during Account Verification

---

src/main/java/mat/cql/CqlParser.java
src/main/java/mat/server/cqlparser/CQLLinter.java

These issues came out of Measure Dev testing. Trying to get them in for drop 3.
- Defines can contain empty lines if they are in the middle of the logic. 
- Changed warning about what a user can modify if it's FHIR after changing cql in the editor.

MAT-993 Add/Edit bug fixes. 

---

README.md
war/WEB-INF/applicationContext-mail.xml

[MAT-999](https://jira.cms.gov/browse/MAT-999)
- Replaced hardcoded SMTP host with spring property that defaults to `localhost` and can be overriden by a system property named `SMTP_HOST`.

[MAT-999] Make SMTP Host configurable

---

war/WEB-INF/applicationContext-mail.xml

[MAT-999](https://jira.cms.gov/browse/MAT-999)
- Replaced hardcoded SMTP host with spring property that defaults to `localhost` and can be overriden by a system property named `SMTP_HOST`.

 [MAT-999] Make SMTP Host configurable --> master

---

war/js/HarpLogin.js

When a user had authenticated with Okta, but did not have Application permissions, they were being presented a Login page minus the login widget. 
This change will close the Okta session (to prevent redirect loops) and redirect the user to the Support page.
Removed unused properties from Okta widget config.

Sign out of Okta session and redirect to Support page.

---

war/js/HarpLogin.js

When a user had authenticated with Okta, but did not have Application permissions, they were being presented a Login page minus the login widget.
This change will close the Okta session (to prevent redirect loops) and redirect the user to the Support page.
Removed unused properties from Okta widget config.

Sign out of Okta session and redirect to Support page

---

src/main/java/mat/client/Mat.java
src/main/java/mat/client/login/service/HarpService.java
src/main/java/mat/client/login/service/HarpServiceAsync.java
src/main/java/mat/server/HarpServiceImpl.java
src/main/java/mat/server/service/impl/LoginCredentialServiceImpl.java
src/main/java/mat/shared/HarpConstants.java

Use claims from userinfo Instead of relying on the id token when updating user details in MAT. The response from userinfo is easier to parse and more consistent as it is not affected by okta custom authorization server rules.
- Added new `HarpConstant`s for user's given name, middle name, and family name. (Previously, we only had easy access to the user's fullname on the ID Token).
- Added operation to HarpService to call Okta's `/userinfo` endpoint and parse the results into a HashMap with `HarpConstant`s as keys.
- Removed `Mat.java`'s parsing user details from the ID Token. Added call to `HarpService.getUserInfo`, which happens after validating the access token, since it is required, and the result is then saved to `MatContext` so the existing session flow can continue.
- Updated …

[MAT-1058] Use Okta's userinfo endpoint to retrieve user claims (MASTER)

---

src/main/java/mat/client/Mat.java
src/main/java/mat/client/login/service/HarpService.java
src/main/java/mat/client/login/service/HarpServiceAsync.java
src/main/java/mat/server/HarpServiceImpl.java
src/main/java/mat/server/service/impl/LoginCredentialServiceImpl.java
src/main/java/mat/shared/HarpConstants.java

Use claims from userinfo Instead of relying on the id token when updating user details in MAT. The response from userinfo is easier to parse and more consistent as it is not affected by okta custom authorization server rules.
- Added new `HarpConstant`s for user's given name, middle name, and family name. (Previously, we only had easy access to the user's fullname on the ID Token).
- Added operation to HarpService to call Okta's `/userinfo` endpoint and parse the results into a HashMap with `HarpConstant`s as keys.
- Removed `Mat.java`'s parsing user details from the ID Token. Added call to `HarpService.getUserInfo`, which happens after validating the access token, since it is required, and the result is then saved to `MatContext` so the existing session flow can continue.
- Updated …

[MAT-1058] Use Okta's userinfo endpoint to retrieve user claims (develop)

---

.github/workflows/gitleaks_github_actions.yml

This PR upgrades our gitleaks automation to the latest version and points the config to our new SB bmat gitleaks config repo.

Upgrade to Gitleaks 4.3.1 and point to new SB config repo

---

src/main/java/mat/server/service/impl/ZipPackager.java

We should only load cql lib and export if it is fhir.

MAT-1112 Fixed QDM packaging bug.

---

src/main/java/mat/server/util/XmlProcessor.java

Fixes a bug where we were NPE while cloning a FHIR measure if a valueset didn't have a version.

Fixes a bug where we were NPE while cloning a fhir measure if a valueset didn't have a version.

---

src/main/java/mat/client/measure/service/FhirConvertResultResponse.java
src/main/java/mat/server/clause/FhirMeasureRemoteServiceImpl.java
src/main/java/mat/server/service/FhirMeasureService.java
src/main/java/mat/server/service/fhirvalidationreport/MeasureValidationReportImpl.java
src/main/java/mat/server/service/impl/FhirMeasureServiceImpl.java
src/test/java/mat/server/clause/FhirMeasureRemoteServiceImplTest.java
src/test/java/mat/server/service/impl/FhirMeasureServiceImplTest.java
src/test/java/tools/GenerateCommonFhirLibSql.java

A conversion is performed without updating mat DB and then validation is run on the CQL returned.

MAT-1289 Changed to correctly validate fhir for QDM. 

---

src/main/java/mat/server/service/impl/MeasurePackageServiceImpl.java

It was breaking function argument types.

BUGFIX Don't reverse engineer when formatting for FHIR. 

---

src/main/resources/MAT.properties

this change is needed due to hcqis planned cutover to fireeye email filter.  no domain except hcqis.org will forward once on new service

changing "from" address domain to hcqis.org

---

src/main/java/mat/client/measure/AbstractNewMeasureView.java
src/main/java/mat/client/validator/ErrorHandler.java

Updates to stop double reading of field names for New Measure page and to use aria-invalid and aria-describedBy to point to the error message.

BUGFIX 508 Fix for JAWS to hopefully read error messages.

---

pom.xml
src/main/java/mat/server/service/impl/ZipPackager.java

Export measure.id and library.id are now the cql library name.

MAT-2448 Compatibility changes needed for CQFRuler. 

---

src/main/java/mat/client/cqlworkspace/shared/CQLEditorPanel.java

This change removes the Tooltip "CQL Library Editor" 
Technically removing a Title tag, Tested with Google Chrome screen Reader, not impacted
https://jira.cms.gov/browse/MAT-2464

Removed Cql Editor Tooltip

---

src/main/java/mat/server/humanreadable/helper/DataRequirementsNoValueSetFilter.java

Bug Fix
valuesetAndCodeDataCriteriaList.getDatatype() is null so added a null check prior

NPE while retrieving Datatype

---

src/main/java/mat/server/service/fhirvalidationreport/CqlLibraryValidationReportImpl.java
src/main/java/mat/server/service/impl/SimpleEMeasureServiceImpl.java

dataRequirementsNoValueSet should be added only during the generation of FHIR Human Readable. So a check has been added to make sure the measure is FHIR

Bug fix for QDM HR export

---

pom.xml

Reverts MeasureAuthoringTool/MeasureAuthoringTool#521
Liquibase started having issues around the time of this merge. Reverting to verify if this is cause.

Revert "Bump mysql-connector-java from 8.0.22 to 8.0.23"

---

src/main/java/mat/client/CqlLibraryPresenter.java
src/main/java/mat/client/measure/measuredetails/MeasureDetailsPresenter.java
src/main/java/mat/client/shared/ui/DeleteConfirmDialogBox.java

During deletion of Measure, Delete forever button has hard coded text of "Delete Library Forever".
so I changed it to "Delete Measure Forever" for Measure and "Delete Library Forever" for libraries.

Changed Delete button to display appropriate text.

---

pom.xml
src/main/java/cqltoelm/CQLtoELM.java
super-dev-mode/pom.xml

- fix: super-dev-mode/pom.xml to reduce vulnerabilities
- fix: pom.xml to reduce vulnerabilities
- Upgrade cqframework to 1.4.8 to resolve multiple security vulnerabilities
Updating the cqframework dependency in MAT to 1.4.8 to resolve a whole slew of security issues stemming from the Jackson JSON/XML parsing dependencies used by the cqframework.

Update CQFramework Dependency to 1.4.8

---

src/main/java/mat/server/service/impl/SimpleEMeasureServiceImpl.java
src/main/java/mat/server/service/impl/helper/ExportResultParser.java

- Check for DRC in dataRequirement codeFilter during filtering
- Renamed variables related to HR generation
Based on the QMIG, the dataRequirement list should be a unique list of all retrieves with or
without Value Set or Direct Reference Code (DRC).
Update the processor to check for Data Requirements that do not have a DRC and to handle
Data Requirements that do not have a CodeFilter.
Update related variables to better reflect the use case.
[MAT-2731](https://jira.cms.gov/browse/MAT-2731)
**Incorrect HR: Retrieve types are `null`**
**Corrected HR with `null`s replaced with Observation/ServiceRequest as appropriate**

[MAT-2731] Check for Code when identifying Data Requirements that do not have a CodeFilter

---

src/main/java/mat/client/shared/MessageDelegate.java
src/main/java/mat/shared/validator/measure/CommonMeasureValidator.java

MAT-2739: Clarify that special characters are disallowed in CQL Library Names
The CQL Library Name entry field already prohibits special characters.
The error text already calls out underscores and spaces, might as
well call out "special characters" in the text as disallowed.
Spelling and editorial fixes to other error text literals:
- valueset -> value set. ValueSet is the formal FHIR Resource.
[MAT-2739](https://jira.cms.gov/browse/MAT-2739)

[MAT-2739] Enhance the error text for new CQL Library Names

---

.gitignore
mat-cypress/cypress/integration/measures/NewMeasureOptions.spec.js
mat-cypress/cypress/support/MAT/MeasureAndCQLLibraryCreation.js
mat-cypress/cypress/support/index.js
mat-cypress/elements/CreateNewMeasureElements.js
mat-cypress/package.json
src/main/java/mat/client/measure/AbstractNewMeasureView.java
src/main/java/mat/client/measure/DetailDisplay.java
src/main/java/mat/client/measure/ManageMeasurePresenter.java
src/main/java/mat/client/measure/NewCompositeMeasureView.java
src/main/java/mat/client/measure/NewMeasureView.java
src/main/java/mat/client/validator/ErrorHandler.java

**[MAT-2758](https://jira.cms.gov/browse/MAT-2758)**
Split the CQL Library Name option checkbox into two and disable the textbox whenever
the user elects to have the name automatically generated to match the generated
CMS ID.
Splitting the option into its components makes it clearer to the user what affect each option will have on the resulting measure. These checkboxes should only appear on **New** measure and composite measure pages.
Users may elect to generate a CMS/eCQM ID for the measure and, when selected, they may also elect to match the related CQL Library Name with the generated ID. When a user elects to have both the ID and Library Name generated, the Library Name's textbox is disabled and all field level validations are cleared.
The CMS ID and Library Name are generated on …

[MAT-2758] Split up New Measure Name options into separate checkboxes

---

src/main/java/mat/server/humanreadable/HumanReadableGenerator.java

MAT-2586
Adding back the changes made to generate HR using simpleXml instead of measureXml
PR that reverted these changes -> [Reverted PR](https://github.com/MeasureAuthoringTool/MeasureAuthoringTool/pull/545/files)
[MAT-2586](https://jira.cms.gov/browse/MAT-2586)

MAT-2586 rework

---

Dockerfile

While making changes to the Dockerfile, I removed a cert bundle that I thought was no longer needed.  It's still needed for bonnie dev integration.

this cert is needed for bonnie dev integration

---

pom.xml

Set a specific version of jackson-core & jackson-annotations
Latest `jackson-databind` pulls down older versions of `jackson-core` and `jackson-annotations` that aren't compatible with the current version of Spring, and we want the latest `jackson-databind` for its security fixes.

Pull down jackson-annotations dependency

---

src/main/java/mat/server/MeasureLibraryServiceImpl.java
src/main/java/mat/server/service/impl/MeasureCloningServiceImpl.java
src/main/java/mat/server/util/XmlProcessor.java

MAT-2881
On save of Measure Observations for Patient Based Ratio measures, the Heading and the success message is not populated as expected, this is because these UI elements are displayed from the data provided in measure XML. 
- When creating a new measure, MAT will create empty nodes for all possible 'populations' based on 'scoring type' in Measure xml.
- For Patient based ratio measures, these nodes are not created when creating a new measure. Although these nodes are added upon save.
- these empty nodes are necessary to render the UI elements.
[https://jira.cms.gov/browse/MAT-2881](MAT-2881)

BugFix MAT-2881, invalid message on save of MO

---

src/main/java/liquibase/QDM_5_6_MeasureXmlUpdate.xml
src/main/java/liquibase/QDM_5_6_MeasureXmlUpdate_v2.xml
src/main/java/liquibase/changelog.xml

MAT-2833
- Liquibase script to update text in Measure XML for existing QDM draft 5.5 measures. 
- Although QDM_VERSION of these measures are already updated to 5.6. So the query reads QDM_VERSION = '5.6'
- Since the script is written in XML, I have to escape '<' and '>' characters with &lt; and &gt; respectively.
- I added an update statement for StandAlone Cql libraries. so that all draft 5.6 Cql libraries will have ‘5.6’ as text in their Cql. 
- This liquibase script also updated the Model version in the General information tab.
[MAT-2833](https://jira.cms.gov/browse/MAT-2833)

Updated text to 5.6 in measure Xml for existing 5.5 draft measures

---

src/main/java/mat/client/cqlworkspace/EditIncludedLibraryDialogBox.java
src/main/java/mat/model/clause/CQLLibrary.java
src/main/java/mat/server/CQLLibraryService.java

MAT-2832
The revision number of Cql library is retrieved as '0' and is stored in measure XML, but the actual cql library will have '000' as the revision number. This mismatch is causing an issue while replacing the included libraries from helper UI. 
Solution: While retrieving the cql Library, if the revision number is '0' then we are returning '000' instead So that it could be saved as '000' in measure Xml.
[MAT-2832](https://jira.cms.gov/browse/MAT-2832)

Added a check to see if the revision number is '0' instead of '000'

---

pmd.xml
src/main/java/mat/server/CQLServiceImpl.java

Updating DRC handling to check for null code system version before attempting to extract the value from a non-existent element in the measure xml.
This is currently a FHIR only issue, as QDM measures lock DRC changes to the helper UI where the version is maintained in the backing model.
For both FHIR and QDM, when a code system is added to the CQL via the helper UI (by adding a code), its version is maintained in the model regardless of the "include version" option even though the generated CQL will not contain the version if the "include version" option was not selected. For FHIR, saving from the CQL Editor overwrites the DRCs and Code Systems in the back model. Therefore, the backing model will lose the code system version value whenever CQL without the version component is saved from …

[MAT-2824] FHIR: Delete DRCs that reference versionless Code Systems

---

src/main/java/mat/server/ExportServlet.java
src/main/java/mat/server/service/impl/ZipPackager.java
src/main/java/mat/shared/FileNameUtility.java

For QDM measure, when a user exports either of these 3 'cql', 'json', 'xml' and if a zip folder is downloaded, an appropriate keyword is added at the end, so that these folders can be differentiated. 
[MAT-2994](https://jira.cms.gov/browse/MAT-2994)

Added FileNameExtensions for zip folders

---

src/main/java/mat/client/cqlworkspace/CQLMeasureWorkSpacePresenter.java
src/main/java/mat/client/cqlworkspace/CQLStandaloneWorkSpacePresenter.java

Issue: When the user has unsaved changes in Cql Definitions UI, and double clicks on another definition, a busy loading spinner is displayed and never removed.
Solution: When the page is dirty this spinner has to be set to false, but Carson commented it out. We could uncomment the statement where we set it to false, but I observed that this spinner does not have to be set to **true** at the beginning of '_definitionListBoxDoubleClickEvent_' method, the heavy work is done only if page is not dirty to started the spinner in the else part of the condition '_getIsPageDirty_'
[MAT-3002](https://jira.cms.gov/browse/MAT-3002)

Fixed loading spinner for unsaved definitions

---

src/main/java/mat/client/measure/measuredetails/views/GeneralInformationView.java

Reduced Patient-based options happens when a QDM scoring type permitting both Patient-based and episode-of-care based is converted to FHIR where that same scoring type does not support both options.
Eventually, QDM and FHIR Scoring Types will have parity support for patient or non-patient based.

Default Patient-based indicator to No when option size is reduced

---

src/main/java/mat/client/measure/measuredetails/MeasureDetailsPresenter.java

Added a condition for the dirty check to see if the measure is deleted. 
Tested with FHIR, QDM measures, and deleting stand-alone CQL libraries. 
[MAT-3011](https://jira.cms.gov/browse/MAT-3011)

ignoring dirty check if measure is deleted

---

src/main/java/mat/server/humanreadable/HumanReadableGenerator.java

Adding a null check on the ucum attribute in the Measure XML before calling `strip()` to prevent NPE. 
Extracting guard logic into its own method that returns either the ucum value as `scoreUnit` or an empty string, which Freemarker then ignores when generating the Human Readable since it has a length of `0`.

Check the ucum attribute is non-null during HR generation

---

src/main/java/mat/client/MeasureComposerPresenter.java
src/main/java/mat/client/shared/MeasureLockService.java

The issue: When the measure details page is dirty and users tried to navigate, a confirmation warning is prompted, At this stage, if a user deletes the measure, it is deleted in DB, but few operations have to be performed before going back to measure grid. One of which is resetting the measure lock to null. This measure lock is used to make sure that only one user is editing the measure at any given point in time. 
- In this case, we are trying to reset the measure lock for a measure that is already deleted, which is causing the issue. 
Solution: A check has been added to verify if the measure is deleted, before resetting the measure lock.
[MAT-3011](https://jira.cms.gov/browse/MAT-3011)

Fixed issue with unlocking a measure after deleting

---

war/404.jsp
war/WEB-INF/web.xml
war/error.jsp

Set link to prod home page in error pages instead of using relative link to /Mat.html as it can readily fail if the user has navigated to an unsupported path.
Map common 400/500 errors to custom error page. Do not use the defaut tomcat error page as it includes stack trace and server version information that could be used by attackers.

Additional Custom Error Pages

---

server.xml

Disable error report and server info on tomcat generated error pages.

Disable error report and server info on tomcat generated error pages

---

pmd.xml
src/main/java/cqltoelm/MATCQLFilter.java
src/main/java/cqltoelm/models/CQLGraph.java
src/main/java/mat/server/humanreadable/HumanReadableGenerator.java
src/main/java/mat/server/util/CQLUtil.java

When we swapped out the SmimpleXML for the Measure XML as the basis for the Human Readable we lost the define filtering done when generating the SimpleXML (from the Measure XML), which was too restrictive for the Human Readable, but was expected by the Human Readable Generator.
This introduces a simpler filter to ensure only top level Population, Supplemental Data Elements (SDE), and Risk Adjustment Variables (RAV) and their descendants are displayed in the HR, thereby matching the filtering done to the CQL.
Minor changes:
- Clean up utility classes
- Add modified classes to pmd config
[MAT-3030](https://jira.cms.gov/browse/MAT-3030)

[MAT-3030] Ignore Defines not related to top level Population, SDE, or RAV defines

---

src/main/java/mat/client/measure/ManageMeasurePresenter.java

Occasionally, a user can multi-press the save button and generate multiple draft/clones. Most of the time, validation kicks in and rejects the extra requests.
Disable the save and cancel buttons on save click until the operation completes.
[MAT-3042](https://jira.cms.gov/browse/MAT-3042)

[MAT-3042] Disable Save/Cancel during save operation for Draft/Clone

---

src/main/java/mat/client/cqlworkspace/AbstractCQLWorkspacePresenter.java
src/main/java/mat/client/shared/MessageDelegate.java
src/main/java/mat/client/umls/service/VsacApiResult.java
src/main/java/mat/server/VSACApiServImpl.java
src/main/java/mat/server/service/cql/FhirCqlParserService.java
src/main/java/mat/shared/CQLModelValidator.java
src/main/java/mat/vsac/VsacService.java
src/main/java/mat/vsacmodel/BasicResponse.java

Preventing `/` chars was blocking users from using valid DRCs (i.e. kg/m2). Opting to permit any non-whitespace characters instead since the UCUM Code System uses `%`, `{`, `_`, and other special chars.
Adding more descriptive error messages for VSAC 404 and 5XX responses on code lookup requests. The MAT uses int values to map response errors to frontend error displays. To avoid mapping conflicts, the new VSAC error messages map to values >90.
VSAC had to update their service to correctly parse codes with `/`. Codes with `%` and `*`, will continue to be a problem until VSAC applies a long term fix.
[MAT-3054](https://jira.cms.gov/browse/MAT-3054)

[MAT-3054] Permit special characters in DRCs validation and provide more descriptive error messages

---

src/main/java/mat/client/measure/ManageMeasurePresenter.java

The Save/Cancel buttons were remaining disabled whenever a round-trip validation check returned a failure (i.e. Library name already exists in DB).
Re-enable buttons after displaying the error message ensuring they are disabled whenever the validations are successful and the Library is created.
[MAT-3098](https://jira.cms.gov/browse/MAT-3098)

[MAT-3098] Re-enable Save/Cancel Button on Error

---

src/main/java/mat/client/cqlworkspace/CQLMeasureWorkSpacePresenter.java
src/main/java/mat/client/cqlworkspace/CQLStandaloneWorkSpacePresenter.java
src/main/java/mat/shared/StringUtility.java
super-dev-mode/pom.xml

All versioned libraries should have '000' as revision number but for FHIRHelpers library the revision number is set to '001' probably a corrupted data issue. So had a condition to check for a particular revision number while including this library using helper UI. 
Also updated Super-dev-mode pom file with the latest pom, so that both the pom files will be in sync. 
[MAT-3114](https://jira.cms.gov/browse/MAT-3114)

Condition to check for FhirHelpers Revision number

---

src/main/java/mat/server/humanreadable/HumanReadableGenerator.java
src/main/java/mat/server/service/impl/SimpleEMeasureServiceImpl.java
src/main/java/mat/server/util/CQLUtil.java

When a define or function used in the call stack for a population (IPP, Denom, Num, etc) is from an external library (Global, FHIRHelpers, etc), include that define or function in the FHIR Human Readable.
Support for external defines/functions already exists for QDM HRs. This change brings the definition and function lists in the FHIR HR up to parity with QDM HR.
The current FHIR specific logic for generating the list of defines/functions used by the populations does not account for external libraries. Since the similar QDM logic does account for external libraries and is actually model agnostic, remove the FHIR specific logic and use the existing QDM logic in its place.
The call to the FHIR Microservices is still necessary to ensure validation is complete prior to assembling the Human …

[MAT-3226] FHIR HR: Include external Defines/Functions

---

src/main/java/mat/client/MainLayout.java
src/main/java/mat/client/Mat.java
src/main/java/mat/client/shared/MatContext.java

The GWT `createUrlBuilder()` method functions more as a find and replace against the current URL than a new URL builder. This causes any parameters to remain in the built URL, causing issues when logging out from Okta  (where logout URLs must be whitelisted).
Using the Href as a base and stripping away the parameters seems to be the cleanest path to generating a consistent, though environment independent, URL without any parameters or unexpected pathing.
When the frontend request results in a 403, GWT generates a `Throwable` containing the Login.html based on the Spring HttpSecurity configuration. Logging this info is overly verbose and not helpful in researching the issue.
The otka logout flow uses the id token stored in `MatContext`, so the tokens in Local Storage can be removed prior …

[MAT-3232] Strip query params from logout URL

---

src/main/java/liquibase/AddFinalizedDateForFhirLibraries.xml
src/main/java/liquibase/changelog.xml

Finalized dates were null for few standalone versioned libraries, This couldn've happened when manually pushing these global libraries to DB. 
So created a liquibase script to update these already versioned stand alone libraries with appropriate finalized date. 
If a Library has a more than 1 with same SET_ID then the olderst date is asssigned, on the other hand if the library doesn't have mulitple wth same SET_ID then the latest date is added. 
[MAT-3257](https://jira.cms.gov/browse/MAT-3257)

Added finalized date to determine the youngest library in the family

---

src/main/java/mat/server/CQLUtilityClass.java

The CDCREC Code System's FHIR URL is an OID with the `urn:oid` prefix, the first OID based FHIR URL accepted by the MAT. As a result, it is triggering older QDM code that expects the code system OID to come from VSAC without the prefix and adds it to the CQL `codesystem` statement.
The FHIR URL comes from the code system mapping json, instead of VSAC, and the mapping entry is also used for validation, requiring the code system url in the CQL match the mapping entry exactly. Hence, the prefix must be present in the mapping entry.
This will check if the prefix is already present before adding it to the `codesystem` statement.
[MAT-3277](https://jira.cms.gov/browse/MAT-3277)

Check for Code System OID prefix before appending said prefix

---

src/main/java/mat/client/shared/TimeoutManager.java

Increasing the time threshold before displaying an inactivity warning to users to 25 minutes, up from 10 minutes.
Combined with the post-warning threshold of 5 minutes, this change will increase the overall timeout threshold to 30 minutes.
[MAT-2880](https://jira.cms.gov/browse/MAT-2880)

Increase inactivity warning threshold to 25 minutes

---

README.md

Tomcat 10 and Spring versions < 6 are non-compatible. To run MAT on Tomcat 10, the generated WAR must be run through the Tomcat Migration Tool for Jakarta EE.
This is easily accomplished on Tomcat 10 directly by copying the WAR into the `webapps-javaee` directory. From there, Tomcat will pick up the WAR, run it against the migration tool, and move the result to the normal `webapps` dir.
I have yet to find a way to instruct IntelliJ to deploy to specific directory. As a workaround, add the migration tool execution as a pre-deployment step to the Run config.
Adding steps to the README.md to guide developers in setting up the pre-deployment step that runs migration tool and replaces the target WAR with its result.
Signed-off-by: Joseph Kotanchik <joseph.kotanchik@semanticbits.com> …

Add Tomcat 10 instructions to readme

---

src/main/resources/templates/humanreadable/measure_information_table.ftl

The measure score type check around Measure Observation display in the Human Readable was accidentally removed during an update to enable patient-based ratio measures.
Measure Observation metadata should only be displayed in the HR for CV and Ratio measures.

Re-add Measure Scoring type check around MO display in HR

---

src/main/java/mat/client/export/measure/ManageMeasureExportPresenter.java
src/main/java/mat/client/measure/service/MeasureService.java
src/main/java/mat/client/measure/service/MeasureServiceAsync.java
src/main/java/mat/client/shared/MessageDelegate.java
src/main/java/mat/server/MeasureServiceImpl.java
src/main/java/mat/server/util/MeasureTransferUtil.java

…
Display error message if the measure to be transferred has no measure package or it is empty.
MAT-4143 Transfer To Madie button enabled for FHIR converted unpackaged measure

MAT-4143 Transfer To Madie button enabled for FHIR converted unpackaged measure
